spring.application.name=springSample

server.port=8085
welcome.msg=Welcome to the Spring Sample Application

spring.datasource.url=jdbc:sqlserver://FSSRENTAL192:1433;databasename=Test;encrypt=true;trustServerCertificate=true;
spring.datasource.username=myUser
spring.datasource.password=StrongPassword@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
